apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "5"
  creationTimestamp: "2024-12-28T13:52:10Z"
  generation: 5
  labels:
    k8s-app: service1
  name: service1
  namespace: api-gw
  resourceVersion: "5516"
  uid: 490258f4-1e93-44fb-9e42-0ad8432d557f
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: service1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2024-12-28T15:07:37Z"
      creationTimestamp: null
      labels:
        k8s-app: service1
      name: service1
    spec:
      containers:
        - image: basteez/service1
          imagePullPolicy: Never
          name: service1
          resources: { }
          securityContext:
            privileged: false
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: { }
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
    - lastTransitionTime: "2024-12-28T13:57:40Z"
      lastUpdateTime: "2024-12-28T13:57:40Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    - lastTransitionTime: "2024-12-28T13:52:10Z"
      lastUpdateTime: "2024-12-28T15:07:38Z"
      message: ReplicaSet "service1-84bb9766b8" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
  observedGeneration: 5
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
