apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
  creationTimestamp: "2024-12-28T14:00:55Z"
  generation: 2
  labels:
    k8s-app: service2
  name: service2
  namespace: api-gw
  resourceVersion: "1684"
  uid: 52cb8a90-e4c7-423e-b563-25ac5a4b7b65
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: service2
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: service2
      name: service2
    spec:
      containers:
        - image: basteez/service2
          imagePullPolicy: Never
          name: service2
          resources: { }
          securityContext:
            privileged: false
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: { }
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
    - lastTransitionTime: "2024-12-28T14:01:13Z"
      lastUpdateTime: "2024-12-28T14:01:13Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    - lastTransitionTime: "2024-12-28T14:00:55Z"
      lastUpdateTime: "2024-12-28T14:01:13Z"
      message: ReplicaSet "service2-dd66cb86c" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
